# Uncomment the next line to define a global platform for your project
# Key ca-app-pub-7535231596532581~7544425753
platform :ios, '10.3'

target 'ToDo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ToDo
  pod 'RealmSwift'
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
